<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Family;
use App\Models\FamilyMember;
use Carbon\Carbon;

class FamilySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Data keluarga
        $families = [
            [
                'number_kk' => '2172011404990001',
                'ownership_kk' => 'KK',
                'number_of_family_member' => 4,
                'rt_address' => 'RT 001 RW 001',
                'ktp_address' => 'Jl. Yossudarso No. 10',
                'city_address' => 'Tanjungpinang',
                'latitude' => 1.1428,
                'longitude' => 104.0443,
                'bpnt' => 'Ya',
                'pkh' => 'Ya',
                'blt_elderly' => 'Tidak',
                'blt_village' => 'Tidak',
                'other_assistance' => 'Tidak',
                'house_photo' => null,
                'members' => [
                    [
                        'full_name' => 'Ahmad Fauzi',
                        'nik' => '2172011404990101',
                        'status_in_family' => 'Kepala Keluarga',
                        'place_of_birth' => 'Tanjungpinang',
                        'date_of_birth' => '1980-05-15',
                        'gender' => 'Laki-laki',
                        'marital_status' => 'Kawin',
                        'ethnic' => 'Melayu',
                        'highest_education_level' => 'S1/Diploma IV',
                        'highest_education_certificate' => 'S1/Diploma IV',
                        'employment_status' => 'Bekerja',
                        'employment_position' => 'PNS/TNI/POLRI/Pegawai BUMN',
                        'main_occupation' => 'PNS',
                        'health_insurance' => 'BPJS Kesehatan PBI',
                        'stunting' => 'Tidak',
                        'disability' => 'Tidak',
                    ],
                    [
                        'full_name' => 'Siti Aminah',
                        'nik' => '2172011404990102',
                        'status_in_family' => 'Istri/Suami',
                        'place_of_birth' => 'Tanjungpinang',
                        'date_of_birth' => '1985-08-20',
                        'gender' => 'Perempuan',
                        'marital_status' => 'Kawin',
                        'ethnic' => 'Melayu',
                        'highest_education_level' => 'SMA/MA/SMLB/PAKET C',
                        'highest_education_certificate' => 'SMA/MA/SMLB/PAKET C',
                        'employment_status' => 'Mengurus Rumah Tangga',
                        'employment_position' => 'Pekerja tidak dibayar',
                        'main_occupation' => 'Ibu Rumah Tangga',
                        'health_insurance' => 'BPJS Kesehatan PBI',
                        'stunting' => 'Tidak',
                        'disability' => 'Tidak',
                    ],
                    [
                        'full_name' => 'Muhammad Rizki',
                        'nik' => '2172011404990103',
                        'status_in_family' => 'Anak',
                        'place_of_birth' => 'Tanjungpinang',
                        'date_of_birth' => '2010-03-10',
                        'gender' => 'Laki-laki',
                        'marital_status' => 'Belum kawin',
                        'ethnic' => 'Melayu',
                        'highest_education_level' => 'SD/MI/SDLB/PAKET A',
                        'highest_education_certificate' => 'SD/MI/SDLB/PAKET A',
                        'employment_status' => 'Sekolah',
                        'employment_position' => 'Pekerja tidak dibayar',
                        'main_occupation' => 'Pelajar',
                        'health_insurance' => 'BPJS Kesehatan PBI',
                        'stunting' => 'Tidak',
                        'disability' => 'Tidak',
                    ],
                    [
                        'full_name' => 'Aisyah Putri',
                        'nik' => '2172011404990104',
                        'status_in_family' => 'Anak',
                        'place_of_birth' => 'Tanjungpinang',
                        'date_of_birth' => '2015-07-25',
                        'gender' => 'Perempuan',
                        'marital_status' => 'Belum kawin',
                        'ethnic' => 'Melayu',
                        'highest_education_level' => 'SD/MI/SDLB/PAKET A',
                        'highest_education_certificate' => 'SD/MI/SDLB/PAKET A',
                        'employment_status' => 'Sekolah',
                        'employment_position' => 'Pekerja tidak dibayar',
                        'main_occupation' => 'Pelajar',
                        'health_insurance' => 'BPJS Kesehatan PBI',
                        'stunting' => 'Tidak',
                        'disability' => 'Tidak',
                    ],
                ]
            ],
            [
                'number_kk' => '2172011404990002',
                'ownership_kk' => 'KK',
                'number_of_family_member' => 3,
                'rt_address' => 'RT 001 RW 001',
                'ktp_address' => 'Jl. Ahmad Yani No. 25',
                'city_address' => 'Tanjungpinang',
                'latitude' => 1.1435,
                'longitude' => 104.0450,
                'bpnt' => 'Ya',
                'pkh' => 'Tidak',
                'blt_elderly' => 'Ya',
                'blt_village' => 'Tidak',
                'other_assistance' => 'Tidak',
                'house_photo' => null,
                'members' => [
                    [
                        'full_name' => 'Budi Santoso',
                        'nik' => '2172011404990201',
                        'status_in_family' => 'Kepala Keluarga',
                        'place_of_birth' => 'Tanjungpinang',
                        'date_of_birth' => '1975-02-10',
                        'gender' => 'Laki-laki',
                        'marital_status' => 'Kawin',
                        'ethnic' => 'Jawa',
                        'highest_education_level' => 'SMA/MA/SMLB/PAKET C',
                        'highest_education_certificate' => 'SMA/MA/SMLB/PAKET C',
                        'employment_status' => 'Bekerja',
                        'employment_position' => 'Buruh/Karyawan/Pegawai Swasta',
                        'main_occupation' => 'Karyawan Swasta',
                        'health_insurance' => 'BPJS Kesehatan Non PBI/Mandiri',
                        'stunting' => 'Tidak',
                        'disability' => 'Tidak',
                    ],
                    [
                        'full_name' => 'Dewi Lestari',
                        'nik' => '2172011404990202',
                        'status_in_family' => 'Istri/Suami',
                        'place_of_birth' => 'Tanjungpinang',
                        'date_of_birth' => '1978-06-18',
                        'gender' => 'Perempuan',
                        'marital_status' => 'Kawin',
                        'ethnic' => 'Jawa',
                        'highest_education_level' => 'SMP/MTS/SMPLB/PAKET B',
                        'highest_education_certificate' => 'SMP/MTS/SMPLB/PAKET B',
                        'employment_status' => 'Bekerja',
                        'employment_position' => 'Berusaha',
                        'main_occupation' => 'Pedagang',
                        'health_insurance' => 'Tidak memiliki',
                        'stunting' => 'Tidak',
                        'disability' => 'Tidak',
                    ],
                    [
                        'full_name' => 'Eko Prasetyo',
                        'nik' => '2172011404990203',
                        'status_in_family' => 'Anak',
                        'place_of_birth' => 'Tanjungpinang',
                        'date_of_birth' => '2005-11-30',
                        'gender' => 'Laki-laki',
                        'marital_status' => 'Belum kawin',
                        'ethnic' => 'Jawa',
                        'highest_education_level' => 'SMA/MA/SMLB/PAKET C',
                        'highest_education_certificate' => 'SMA/MA/SMLB/PAKET C',
                        'employment_status' => 'Sekolah',
                        'employment_position' => 'Pekerja tidak dibayar',
                        'main_occupation' => 'Pelajar',
                        'health_insurance' => 'Tidak memiliki',
                        'stunting' => 'Tidak',
                        'disability' => 'Tidak',
                    ],
                ]
            ],
            [
                'number_kk' => '2172011404990003',
                'ownership_kk' => 'KK',
                'number_of_family_member' => 2,
                'rt_address' => 'RT 002 RW 001',
                'ktp_address' => 'Jl. Merdeka No. 15',
                'city_address' => 'Tanjungpinang',
                'latitude' => 1.1442,
                'longitude' => 104.0455,
                'bpnt' => 'Tidak',
                'pkh' => 'Ya',
                'blt_elderly' => 'Tidak',
                'blt_village' => 'Ya',
                'other_assistance' => 'Bantuan Sembako',
                'house_photo' => null,
                'members' => [
                    [
                        'full_name' => 'Rina Wati',
                        'nik' => '2172011404990301',
                        'status_in_family' => 'Kepala Keluarga',
                        'place_of_birth' => 'Tanjungpinang',
                        'date_of_birth' => '1990-03-22',
                        'gender' => 'Perempuan',
                        'marital_status' => 'Cerai mati',
                        'ethnic' => 'Sunda',
                        'highest_education_level' => 'Diploma I/II/III',
                        'highest_education_certificate' => 'Diploma I/II/III',
                        'employment_status' => 'Bekerja',
                        'employment_position' => 'PNS/TNI/POLRI/Pegawai BUMN',
                        'main_occupation' => 'Pegawai Bank',
                        'health_insurance' => 'BPJS Kesehatan Non PBI/Mandiri',
                        'stunting' => 'Tidak',
                        'disability' => 'Tidak',
                    ],
                    [
                        'full_name' => 'Joko Susilo',
                        'nik' => '2172011404990302',
                        'status_in_family' => 'Anak',
                        'place_of_birth' => 'Tanjungpinang',
                        'date_of_birth' => '2018-09-05',
                        'gender' => 'Laki-laki',
                        'marital_status' => 'Belum kawin',
                        'ethnic' => 'Sunda',
                        'highest_education_level' => 'SD/MI/SDLB/PAKET A',
                        'highest_education_certificate' => 'SD/MI/SDLB/PAKET A',
                        'employment_status' => 'Sekolah',
                        'employment_position' => 'Pekerja tidak dibayar',
                        'main_occupation' => 'Pelajar',
                        'health_insurance' => 'BPJS Kesehatan Non PBI/Mandiri',
                        'stunting' => 'Tidak',
                        'disability' => 'Tidak',
                    ],
                ]
            ],
            [
                'number_kk' => '2172011404990004',
                'ownership_kk' => 'Non KK',
                'number_of_family_member' => 3,
                'rt_address' => 'RT 002 RW 002',
                'ktp_address' => 'Jl. Sudirman No. 8',
                'city_address' => 'Batam',
                'latitude' => 1.1450,
                'longitude' => 104.0460,
                'bpnt' => 'Tidak',
                'pkh' => 'Tidak',
                'blt_elderly' => 'Ya',
                'blt_village' => 'Tidak',
                'other_assistance' => 'Tidak',
                'house_photo' => null,
                'members' => [
                    [
                        'full_name' => 'Maman Suherman',
                        'nik' => '2172011404990401',
                        'status_in_family' => 'Kepala Keluarga',
                        'place_of_birth' => 'Tanjungpinang',
                        'date_of_birth' => '1960-12-01',
                        'gender' => 'Laki-laki',
                        'marital_status' => 'Kawin',
                        'ethnic' => 'Sunda',
                        'highest_education_level' => 'SD/MI/SDLB/PAKET A',
                        'highest_education_certificate' => 'SD/MI/SDLB/PAKET A',
                        'employment_status' => 'Tidak bekerja',
                        'employment_position' => 'Pekerja tidak dibayar',
                        'main_occupation' => 'Tidak bekerja',
                        'health_insurance' => 'BPJS Kesehatan PBI',
                        'stunting' => 'Tidak',
                        'disability' => 'Tidak',
                    ],
                    [
                        'full_name' => 'Tati Sumiati',
                        'nik' => '2172011404990402',
                        'status_in_family' => 'Istri/Suami',
                        'place_of_birth' => 'Tanjungpinang',
                        'date_of_birth' => '1965-04-12',
                        'gender' => 'Perempuan',
                        'marital_status' => 'Kawin',
                        'ethnic' => 'Sunda',
                        'highest_education_level' => 'SD/MI/SDLB/PAKET A',
                        'highest_education_certificate' => 'SD/MI/SDLB/PAKET A',
                        'employment_status' => 'Tidak bekerja',
                        'employment_position' => 'Pekerja tidak dibayar',
                        'main_occupation' => 'Tidak bekerja',
                        'health_insurance' => 'BPJS Kesehatan PBI',
                        'stunting' => 'Tidak',
                        'disability' => 'Tidak',
                    ],
                    [
                        'full_name' => 'Asep Kurniawan',
                        'nik' => '2172011404990403',
                        'status_in_family' => 'Anak',
                        'place_of_birth' => 'Tanjungpinang',
                        'date_of_birth' => '1995-07-08',
                        'gender' => 'Laki-laki',
                        'marital_status' => 'Belum kawin',
                        'ethnic' => 'Sunda',
                        'highest_education_level' => 'S1/Diploma IV',
                        'highest_education_certificate' => 'S1/Diploma IV',
                        'employment_status' => 'Bekerja',
                        'employment_position' => 'Pekerja bebas (Freelance)',
                        'main_occupation' => 'Freelancer IT',
                        'health_insurance' => 'BPJS Kesehatan Non PBI/Mandiri',
                        'stunting' => 'Tidak',
                        'disability' => 'Tidak',
                    ],
                ]
            ],
            [
                'number_kk' => '2172011404990005',
                'ownership_kk' => 'KK',
                'number_of_family_member' => 4,
                'rt_address' => 'RT 001 RW 006',
                'ktp_address' => 'Jl. Diponegoro No. 45',
                'city_address' => 'Tanjungpinang',
                'latitude' => 1.1420,
                'longitude' => 104.0435,
                'bpnt' => 'Ya',
                'pkh' => 'Ya',
                'blt_elderly' => 'Tidak',
                'blt_village' => 'Ya',
                'other_assistance' => 'Tidak',
                'house_photo' => null,
                'members' => [
                    [
                        'full_name' => 'Hendra Wijaya',
                        'nik' => '2172011404990501',
                        'status_in_family' => 'Kepala Keluarga',
                        'place_of_birth' => 'Tanjungpinang',
                        'date_of_birth' => '1982-01-15',
                        'gender' => 'Laki-laki',
                        'marital_status' => 'Kawin',
                        'ethnic' => 'Tionghoa',
                        'highest_education_level' => 'S2',
                        'highest_education_certificate' => 'S2',
                        'employment_status' => 'Bekerja',
                        'employment_position' => 'PNS/TNI/POLRI/Pegawai BUMN',
                        'main_occupation' => 'Dosen',
                        'health_insurance' => 'BPJS Kesehatan Non PBI/Mandiri',
                        'stunting' => 'Tidak',
                        'disability' => 'Tidak',
                    ],
                    [
                        'full_name' => 'Linda Kusuma',
                        'nik' => '2172011404990502',
                        'status_in_family' => 'Istri/Suami',
                        'place_of_birth' => 'Tanjungpinang',
                        'date_of_birth' => '1985-09-20',
                        'gender' => 'Perempuan',
                        'marital_status' => 'Kawin',
                        'ethnic' => 'Tionghoa',
                        'highest_education_level' => 'S1/Diploma IV',
                        'highest_education_certificate' => 'S1/Diploma IV',
                        'employment_status' => 'Bekerja',
                        'employment_position' => 'Buruh/Karyawan/Pegawai Swasta',
                        'main_occupation' => 'Manajer Marketing',
                        'health_insurance' => 'BPJS Kesehatan Non PBI/Mandiri',
                        'stunting' => 'Tidak',
                        'disability' => 'Tidak',
                    ],
                    [
                        'full_name' => 'Kevin Wijaya',
                        'nik' => '2172011404990503',
                        'status_in_family' => 'Anak',
                        'place_of_birth' => 'Tanjungpinang',
                        'date_of_birth' => '2012-11-05',
                        'gender' => 'Laki-laki',
                        'marital_status' => 'Belum kawin',
                        'ethnic' => 'Tionghoa',
                        'highest_education_level' => 'SD/MI/SDLB/PAKET A',
                        'highest_education_certificate' => 'SD/MI/SDLB/PAKET A',
                        'employment_status' => 'Sekolah',
                        'employment_position' => 'Pekerja tidak dibayar',
                        'main_occupation' => 'Pelajar',
                        'health_insurance' => 'BPJS Kesehatan Non PBI/Mandiri',
                        'stunting' => 'Tidak',
                        'disability' => 'Tidak',
                    ],
                    [
                        'full_name' => 'Jessica Wijaya',
                        'nik' => '2172011404990504',
                        'status_in_family' => 'Anak',
                        'place_of_birth' => 'Tanjungpinang',
                        'date_of_birth' => '2015-06-12',
                        'gender' => 'Perempuan',
                        'marital_status' => 'Belum kawin',
                        'ethnic' => 'Tionghoa',
                        'highest_education_level' => 'SD/MI/SDLB/PAKET A',
                        'highest_education_certificate' => 'SD/MI/SDLB/PAKET A',
                        'employment_status' => 'Sekolah',
                        'employment_position' => 'Pekerja tidak dibayar',
                        'main_occupation' => 'Pelajar',
                        'health_insurance' => 'BPJS Kesehatan Non PBI/Mandiri',
                        'stunting' => 'Tidak',
                        'disability' => 'Tidak',
                    ],
                ]
            ],
        ];

        foreach ($families as $familyData) {
            $members = $familyData['members'];
            unset($familyData['members']);
            
            $familyData['created_by'] = 1; // Admin user ID
            $familyData['created_at'] = Carbon::now();
            $familyData['updated_at'] = Carbon::now();
            
            $family = Family::create($familyData);
            
            foreach ($members as $memberData) {
                $memberData['family_id'] = $family->id;
                $memberData['created_at'] = Carbon::now();
                $memberData['updated_at'] = Carbon::now();
                
                // Format tanggal ke Y-m-d untuk database
                if (isset($memberData['date_of_birth'])) {
                    $memberData['date_of_birth'] = Carbon::parse($memberData['date_of_birth'])->format('Y-m-d');
                }
                
                FamilyMember::create($memberData);
            }
        }

        $this->command->info('5 keluarga dengan anggota berhasil dibuat!');
    }
}